In [73]:
!pip install numpy

In [74]:
import numpy as np

### The Basics

In [75]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [76]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [77]:
# Get Dimension
a.ndim

1

In [78]:
# Get Shape
b.shape

(2, 3)

In [79]:
# Get Type
a.dtype

dtype('int32')

In [80]:
# Get Size
a.itemsize

4

In [81]:
# Get total size
a.nbytes

12

In [82]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [83]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [84]:
# Get a specific element [r, c]
a[1, 5]

13

In [85]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [86]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [87]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [88]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [89]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [90]:
# Get specific element (work outside in)
b[0,1,1]

4

In [91]:
# replace 
# b[:,1,:] = [[9,9,9],[8,8]]
b[:,1,:] 

array([[3, 4],
       [7, 8]])

In [92]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Initializing Different Types of Arrays

In [93]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [94]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [95]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [96]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [97]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.80048745, 0.07637161],
       [0.47510794, 0.05487134],
       [0.40396484, 0.94171762],
       [0.9364381 , 0.76420427]])

In [98]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-2, -1,  6],
       [ 5,  2, -1],
       [-3, -4,  0]])

In [99]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [100]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [101]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [102]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### Mathematics

In [103]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [104]:
a + 2

array([3, 4, 5, 6])

In [105]:
a - 2

array([-1,  0,  1,  2])

In [106]:
a * 2

array([2, 4, 6, 8])

In [107]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [108]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [109]:
a ** 2

array([ 1,  4,  9, 16])

In [110]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [111]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [112]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [113]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [114]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [115]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
np.min(stats)

1

In [117]:
np.max(stats, axis=1)

array([3, 6])

In [118]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [119]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [120]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [121]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [122]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

OSError: ignored

##### Boolean Masking and Advanced Indexing

In [ ]:
(~((filedata > 50) & (filedata < 100)))